name: C++ Compilation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: ./.github/workflows/setup.sh

    - name: Build and Run
      run: ./.github/workflows/run.sh

    - name: Lint with clang-tidy
      run: ./.github/workflows/lint.sh

    - name: Format with clang-format
      run: ./.github/workflows/format.sh
