name: C++ Compilation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang cmake

    - name: Build and Run
      run: |
        cd tour_2nd_stroustrup
        if [ -f "CMakeLists.txt" ]; then
          cmake .
          make
        else
          make
          #clang++ -std=c++17 -O3 -Wall -Wextra -o main *.cpp
        fi
        ./main